version: '3.3'

services:
  PostgreSQL:
    restart: always
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true
      - PGDATABASE=lo54
      - PGUSER=postgres
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql #sql script to create tables at entrypoint